spring:
  application:
    name: video-service
  datasource:
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/video?createDatabaseIfNotExist=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: root
      password: 56215487
    postgresql:
      driverClassName: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/test?createDatabaseIfNotExist=true
      username: postgres
      password: 56215487
    hikari:
      minimum-idle: 1
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: AdvZuulHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      mysql-dialect: org.hibernate.dialect.MySQL5Dialect
      postgresql-dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  properties:
     hibernate:
        format-sql: true
server:
  port: 1221